import { Topic } from '@/core/state/store.types'

export type TopicCategory = 'พื้นฐาน' | 'แคลคูลัส' | 'พีชคณิต' | 'สถิติ&ความน่าจะเป็น' | 'ขั้นสูง'

export interface TopicWithCategory extends Topic {
  category: TopicCategory
  descTh: string
}

export const TOPICS: TopicWithCategory[] = [
  // ── พื้นฐาน ──────────────────────────────────────────────────────────
  {
    id: 'arithmetic',
    th: 'เลขคณิต',
    jp: '算術',
    lv: 'easy',
    icon: '±',
    color: 'gold',
    category: 'พื้นฐาน',
    descTh: 'บวก ลบ คูณ หาร เศษส่วน ทศนิยม',
  },
  {
    id: 'algebra',
    th: 'พีชคณิต',
    jp: '代数',
    lv: 'easy',
    icon: 'x²',
    color: 'gold',
    category: 'พื้นฐาน',
    descTh: 'สมการ นิพจน์ พหุนาม',
  },
  {
    id: 'geometry',
    th: 'เรขาคณิต',
    jp: '幾何',
    lv: 'easy',
    icon: '△',
    color: 'blue',
    category: 'พื้นฐาน',
    descTh: 'รูปทรง พื้นที่ ปริมาตร ทฤษฎีพีทาโกรัส',
  },
  {
    id: 'trigonometry',
    th: 'ตรีโกณมิติ',
    jp: '三角',
    lv: 'easy',
    icon: 'sin',
    color: 'teal',
    category: 'พื้นฐาน',
    descTh: 'sin, cos, tan และเอกลักษณ์',
  },
  {
    id: 'functions',
    th: 'ฟังก์ชัน',
    jp: '関数',
    lv: 'easy',
    icon: 'f(x)',
    color: 'purple',
    category: 'พื้นฐาน',
    descTh: 'โดเมน เรนจ์ ฟังก์ชันผกผัน',
  },
  {
    id: 'exponents',
    th: 'เลขยกกำลัง & ล็อก',
    jp: '指数対数',
    lv: 'easy',
    icon: 'logₐ',
    color: 'accent',
    category: 'พื้นฐาน',
    descTh: 'กฎเลขยกกำลัง ลอการิทึม เนเปียร์',
  },
  {
    id: 'number_theory',
    th: 'ทฤษฎีจำนวน',
    jp: '数論',
    lv: 'medium',
    icon: 'ℤ',
    color: 'blue',
    category: 'พื้นฐาน',
    descTh: 'จำนวนเฉพาะ ห.ร.ม. ค.ร.น. การหารลงตัว',
  },
  {
    id: 'complex_numbers',
    th: 'จำนวนเชิงซ้อน',
    jp: '複素数',
    lv: 'medium',
    icon: 'i',
    color: 'purple',
    category: 'พื้นฐาน',
    descTh: 'จำนวนจินตภาพ รูปขั้ว ทฤษฎีบทเดอมัวฟร์',
  },
  {
    id: 'sequences_series',
    th: 'ลำดับและอนุกรม',
    jp: '数列',
    lv: 'medium',
    icon: 'Σn',
    color: 'teal',
    category: 'พื้นฐาน',
    descTh: 'AP, GP, อนุกรมเลขคณิต เรขาคณิต',
  },

  // ── แคลคูลัส ─────────────────────────────────────────────────────────
  {
    id: 'limit',
    th: 'ลิมิต',
    jp: '極限',
    lv: 'easy',
    icon: 'lim',
    color: 'purple',
    category: 'แคลคูลัส',
    descTh: 'ขีดจำกัด ความต่อเนื่อง กฎลอปิตาล',
  },
  {
    id: 'derivative',
    th: 'อนุพันธ์',
    jp: '微分',
    lv: 'easy',
    icon: '∂',
    color: 'accent',
    category: 'แคลคูลัส',
    descTh: 'กฎลูกโซ่ อนุพันธ์ย่อย การหาค่าสุดขีด',
  },
  {
    id: 'integral',
    th: 'อินทิกรัล',
    jp: '積分',
    lv: 'medium',
    icon: '∫',
    color: 'blue',
    category: 'แคลคูลัส',
    descTh: 'อินทิกรัลไม่จำกัดเขต จำกัดเขต เนื้อที่',
  },
  {
    id: 'multivariable_calc',
    th: 'แคลคูลัสหลายตัวแปร',
    jp: '多変数微積分',
    lv: 'hard',
    icon: '∇',
    color: 'teal',
    category: 'แคลคูลัส',
    descTh: 'Gradient, Curl, Divergence, อินทิกรัลซ้อน',
  },
  {
    id: 'differential_eq',
    th: 'สมการเชิงอนุพันธ์',
    jp: '微分方程式',
    lv: 'hard',
    icon: "y'",
    color: 'accent',
    category: 'แคลคูลัส',
    descTh: 'ODE, การแยกตัวแปร, สมการเชิงเส้น',
  },
  {
    id: 'series_convergence',
    th: 'อนุกรมและการลู่เข้า',
    jp: '級数収束',
    lv: 'hard',
    icon: 'Σ∞',
    color: 'purple',
    category: 'แคลคูลัส',
    descTh: 'อนุกรมเทย์เลอร์ แมคลอริน ทดสอบการลู่เข้า',
  },

  // ── พีชคณิต ──────────────────────────────────────────────────────────
  {
    id: 'linear_algebra',
    th: 'พีชคณิตเชิงเส้น',
    jp: '線形代数',
    lv: 'medium',
    icon: '[A]',
    color: 'blue',
    category: 'พีชคณิต',
    descTh: 'เมทริกซ์ ดีเทอร์มิแนนต์ ระบบสมการ',
  },
  {
    id: 'vectors',
    th: 'เวกเตอร์',
    jp: 'ベクトル',
    lv: 'medium',
    icon: '→v',
    color: 'teal',
    category: 'พีชคณิต',
    descTh: 'ดอทโปรดักต์ ครอสโปรดักต์ ระยะทาง',
  },
  {
    id: 'eigenvalues',
    th: 'ค่าไอเกน',
    jp: '固有値',
    lv: 'hard',
    icon: 'λv',
    color: 'gold',
    category: 'พีชคณิต',
    descTh: 'Eigenvalue, Eigenvector, Diagonalization',
  },
  {
    id: 'set_theory',
    th: 'ทฤษฎีเซต',
    jp: '集合論',
    lv: 'easy',
    icon: '∈',
    color: 'purple',
    category: 'พีชคณิต',
    descTh: 'ยูเนียน อินเตอร์เซกชัน คอมพลีเมนต์',
  },
  {
    id: 'polynomial',
    th: 'พหุนาม',
    jp: '多項式',
    lv: 'medium',
    icon: 'pⁿ',
    color: 'accent',
    category: 'พีชคณิต',
    descTh: 'ทฤษฎีบทหารยาว การแยกตัวประกอบ รากของสมการ',
  },

  // ── สถิติ & ความน่าจะเป็น ─────────────────────────────────────────────
  {
    id: 'probability',
    th: 'ความน่าจะเป็น',
    jp: '確率',
    lv: 'medium',
    icon: 'P',
    color: 'accent',
    category: 'สถิติ&ความน่าจะเป็น',
    descTh: 'ความน่าจะเป็น กฎคูณ กฎบาเยส',
  },
  {
    id: 'statistics',
    th: 'สถิติเชิงพรรณา',
    jp: '統計',
    lv: 'easy',
    icon: 'x̄',
    color: 'purple',
    category: 'สถิติ&ความน่าจะเป็น',
    descTh: 'ค่าเฉลี่ย มัธยฐาน ส่วนเบี่ยงเบนมาตรฐาน',
  },
  {
    id: 'combinatorics',
    th: 'การจัดหมู่และวิธีนับ',
    jp: '組み合わせ',
    lv: 'medium',
    icon: 'C(n,r)',
    color: 'blue',
    category: 'สถิติ&ความน่าจะเป็น',
    descTh: 'Permutation, Combination, Binomial',
  },
  {
    id: 'distributions',
    th: 'การแจกแจงความน่าจะเป็น',
    jp: '確率分布',
    lv: 'hard',
    icon: 'N(μ,σ)',
    color: 'teal',
    category: 'สถิติ&ความน่าจะเป็น',
    descTh: 'Normal, Binomial, Poisson, Exponential',
  },
  {
    id: 'inferential_stats',
    th: 'สถิติเชิงอนุมาน',
    jp: '推計統計',
    lv: 'hard',
    icon: 'H₀',
    color: 'gold',
    category: 'สถิติ&ความน่าจะเป็น',
    descTh: 'การทดสอบสมมติฐาน ช่วงเชื่อมั่น t-test',
  },

  // ── ขั้นสูง ───────────────────────────────────────────────────────────
  {
    id: 'discrete_math',
    th: 'คณิตศาสตร์ไม่ต่อเนื่อง',
    jp: '離散数学',
    lv: 'hard',
    icon: '∀',
    color: 'blue',
    category: 'ขั้นสูง',
    descTh: 'Logic, Graph Theory, Recurrence Relations',
  },
  {
    id: 'real_analysis',
    th: 'การวิเคราะห์เชิงจริง',
    jp: '実解析',
    lv: 'hard',
    icon: 'ε-δ',
    color: 'accent',
    category: 'ขั้นสูง',
    descTh: 'การพิสูจน์ขีดจำกัด ความต่อเนื่อง Cauchy',
  },
  {
    id: 'numerical_methods',
    th: 'ระเบียบวิธีเชิงตัวเลข',
    jp: '数値解析',
    lv: 'hard',
    icon: 'Δx',
    color: 'teal',
    category: 'ขั้นสูง',
    descTh: 'Newton-Raphson, Simpson, Euler',
  },
  {
    id: 'fourier',
    th: 'อนุกรมฟูเรียร์',
    jp: 'フーリエ',
    lv: 'hard',
    icon: 'F̂',
    color: 'purple',
    category: 'ขั้นสูง',
    descTh: 'Fourier Series, Transform, Frequency Analysis',
  },
]

export const TOPIC_CATEGORIES: TopicCategory[] = [
  'พื้นฐาน',
  'แคลคูลัส',
  'พีชคณิต',
  'สถิติ&ความน่าจะเป็น',
  'ขั้นสูง',
]

export const CATEGORY_DISPLAY: Record<TopicCategory, { label: string; labelEn: string; color: string }> = {
  'พื้นฐาน':              { label: 'พื้นฐาน',          labelEn: 'Fundamentals', color: 'text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800/40' },
  'แคลคูลัส':             { label: 'แคลคูลัส',         labelEn: 'Calculus',     color: 'text-red-700 dark:text-red-400 bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800/40' },
  'พีชคณิต':              { label: 'พีชคณิต',          labelEn: 'Algebra',      color: 'text-blue-700 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800/40' },
  'สถิติ&ความน่าจะเป็น':  { label: 'สถิติ & ความน่าจะเป็น', labelEn: 'Stats & Prob', color: 'text-purple-700 dark:text-purple-400 bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800/40' },
  'ขั้นสูง':              { label: 'ขั้นสูง',          labelEn: 'Advanced',     color: 'text-slate-700 dark:text-slate-300 bg-slate-100 dark:bg-slate-800/50 border-slate-200 dark:border-slate-700' },
}
